backend:
  name: github
  repo: ampani13/amiya-portfolio
  branch: main
  auth_scope: repo
  oauth_client_id: YOUR_CLIENT_ID_HERE

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "summary"
    label: "Professional Summary"
    files:
      - label: "Summary"
        name: "summary"
        file: "content/summary.md"
        fields:
          - {label: "Summary", name: "body", widget: "markdown"}

  - name: "skills"
    label: "Technical Skills"
    files:
      - label: "Skills"
        name: "skills"
        file: "content/skills.yaml"
        fields:
          - {label: "Skill Categories", name: "skills", widget: "list"}

  - name: "experience"
    label: "Experience"
    label_singular: "Job"
    folder: "content/experience"
    create: true
    fields:
      - {label: "Company", name: "company", widget: "string"}
      - {label: "Position", name: "position", widget: "string"}
      - {label: "Duration", name: "duration", widget: "string"}
      - {label: "Details", name: "details", widget: "list"}

  - name: "education"
    label: "Education"
    files:
      - label: "Education"
        name: "education"
        file: "content/education.yaml"
        fields:
          - {label: "Degrees", name: "degrees", widget: "list", fields: [
              {label: "Degree", name: "degree", widget: "string"},
              {label: "Institution", name: "institution", widget: "string"},
              {label: "Years", name: "years", widget: "string"}
            ]}

  - name: "certifications"
    label: "Certifications"
    files:
      - label: "Certifications"
        name: "certifications"
        file: "content/certifications.yaml"
        fields:
          - {label: "Certifications", name: "certs", widget: "list"}

  - name: "achievements"
    label: "Achievements"
    files:
      - label: "Achievements"
        name: "achievements"
        file: "content/achievements.yaml"
        fields:
          - {label: "Achievements", name: "items", widget: "list"}

  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}